// This file was automatically generated by:
//  /home/gveni/Packages/Slicer4-SuperBuild-Debug/SlicerExecutionModel-build/GenerateCLP/bin/GenerateCLP --InputXML /home/gveni/Documents/Segmentation/GraphCutSeg_Slicer/mesh2graph2surfVnet.xml --OutputCxx /home/gveni/Documents/Segmentation/GraphCutSeg_Slicer/mesh2graph2surfVnetCLP.h
//
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>
#include <map>

#include <sstream>

#include "tclap/CmdLine.h"
#include "ModuleProcessInformation.h"

#ifdef WIN32
#define Module_EXPORT __declspec(dllexport)
#else
#define Module_EXPORT 
#endif

#if defined(main) && !defined(REGISTER_TEST)
// If main defined as a preprocessor symbol, redefine it to the expected entry point.
#undef main
#define main ModuleEntryPoint

extern "C" {
  Module_EXPORT char *GetXMLModuleDescription();
  Module_EXPORT int ModuleEntryPoint(int, char*[]);
}
#endif

extern "C" {
Module_EXPORT char XMLModuleDescription[] = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
"<executable>\n"
"    <category>CARMA</category> \n"
"    <title>Mesh to Graph to SurfVnet</title>\n"
"    <description>This module implements an algorithm to automatically segment out the Left Atrium from an LGE-MRI image volume.</description>\n"
"    <version>0.1.0</version>\n"
"    <documentation-url></documentation-url>\n"
"    <license>Slicer</license>\n"
"    <contributor>Gopal Veni, Salma Bengali, Greg Gardner, Alan Morris, Josh Cates, Rob MacLeod, Ross Whitaker</contributor>\n"
"    <acknowledgements><![CDATA[This work was supported by ...]]></acknowledgements>\n"
"    <parameters>\n"
"        <label>IO</label>\n"
"        <description>Input/output parameters</description>\n"
"        <image>\n"
"            <name>inputImage</name>\n"
"            <label>Input Image</label>\n"
"            <index>0</index>\n"
"            <channel>input</channel>\n"
"            <description><![CDATA[Cardiac LGE-MRI image]]></description>\n"
"        </image>\n"
"        <integer>\n"
"            <name>deltaS</name>\n"
"            <label>Smoothness Parameter</label>\n"
"            <index>1</index>\n"
"            <channel>input</channel>\n"
"            <description><![CDATA[Smoothness constraint for a surface]]></description>\n"
"        </integer>\n"
"	<integer>\n"
"            <name>MdlOption</name>\n"
"            <label>Model selection Parameter</label>\n"
"            <index>2</index>\n"
"            <channel>input</channel>\n"
"            <description><![CDATA[Selection of model]]></description>\n"
"        </integer>\n"
"        <image type=\"label\">\n"
"            <name>outputImage</name>\n"
"            <label>Output Image</label>\n"
"            <index>3</index>\n"
"            <channel>output</channel>\n"
"            <description><![CDATA[The segmented output image volume]]></description>\n"
"        </image>\n"
"        <directory>\n"
"            <name>inputDataDirectory</name>\n"
"            <label>Input Data Directory</label>\n"
"            <index>4</index>\n"
"            <channel>input</channel>\n"
"            <description><![CDATA[The directory from which to import data files]]></description>\n"
"            <!--<default>/Users/salmabengali/data/1/</default> -->\n"
"        </directory> \n"
"	 <file>\n"
"            <name>epiMesh</name>\n"
"            <label>Epi Mesh</label>\n"
"            <index>5</index>\n"
"            <channel>output</channel>\n"
"            <description><![CDATA[The epi mesh]]></description>\n"
"        </file>\n"
"        <file>\n"
"            <name>endoMesh</name>\n"
"            <label>Endo Mesh</label>\n"
"            <index>6</index>\n"
"            <channel>output</channel>\n"
"            <description><![CDATA[The endo mesh]]></description>\n"
"        </file>\n"
"	 <float>\n"
"            <name>row</name>\n"
"            <label>Row</label>\n"
"            <index>7</index>\n"
"            <channel>input</channel>\n"
"            <description><![CDATA[Center of mass row]]></description>\n"
"        </float>\n"
"	 <float>\n"
"            <name>column</name>\n"
"            <label>Column</label>\n"
"            <index>8</index>\n"
"            <channel>input</channel>\n"
"            <description><![CDATA[Center of mass column]]></description>\n"
"        </float>\n"
"	 <float>\n"
"            <name>slice</name>\n"
"            <label>Slice</label>\n"
"            <index>9</index>\n"
"            <channel>input</channel>\n"
"            <description><![CDATA[Center of mass Slice]]></description>\n"
"        </float>\n"
"       <!--<file multiple=\"true\">\n"
"            <name>args</name>\n"
"            <index>3</index>\n"
"            <description>The directory from which to import data files</description>\n"
"       </file> -->\n"
"    </parameters>\n"
"</executable>\n"
;

}

void
splitString (const std::string &text,
             const std::string &separators,
             std::vector<std::string> &words)
{
  const std::string::size_type n = text.length();
  std::string::size_type start = text.find_first_not_of(separators);
  while (start < n)
    {
    std::string::size_type stop = text.find_first_of(separators, start);
    if (stop > n) stop = n;
    words.push_back(text.substr(start, stop - start));
    start = text.find_first_not_of(separators, stop+1);
    }
}

void
splitFilenames (const std::string &text,
                std::vector<std::string> &words)
{
  const std::string::size_type n = text.length();
  bool quoted;
  std::string comma(",");
  std::string quote("\"");
  std::string::size_type start = text.find_first_not_of(comma);
  while (start < n)
    {
    quoted = false;
    std::string::size_type startq = text.find_first_of(quote, start);
    std::string::size_type stopq = text.find_first_of(quote, startq+1);
    std::string::size_type stop = text.find_first_of(comma, start);
    if (stop > n) stop = n;
    if (startq != std::string::npos && stopq != std::string::npos)
      {
      while (startq < stop && stop < stopq && stop != n)
         {
         quoted = true;
         stop = text.find_first_of(comma, stop+1);
         if (stop > n) stop = n;
         }
      }
    if (!quoted)
      {
      words.push_back(text.substr(start, stop - start));
      }
    else
      {
      words.push_back(text.substr(start+1, stop - start-2));
      }
    start = text.find_first_not_of(comma, stop+1);
    }
}

char *GetXMLModuleDescription()
{
   return XMLModuleDescription;
}

#define GENERATE_LOGO
#define GENERATE_XML \
  if (argc >= 2 && (strcmp(argv[1],"--xml") == 0)) \
    { \
    std::cout << GetXMLModuleDescription(); \
    return EXIT_SUCCESS; \
    }
#define GENERATE_TCLAP \
    std::string inputImage; \
    int deltaS; \
    int MdlOption; \
    std::string outputImage; \
    std::string inputDataDirectory; \
    std::string epiMesh; \
    std::string endoMesh; \
    float row; \
    float column; \
    float slice; \
    bool echoSwitch = false; \
    bool xmlSwitch = false; \
    std::string processInformationAddressString = "0"; \
    std::string returnParameterFile; \
    std::string fullDescription("Description: "); \
    fullDescription += "This module implements an algorithm to automatically segment out the Left Atrium from an LGE-MRI image volume."; \
    if (!std::string("Gopal Veni, Salma Bengali, Greg Gardner, Alan Morris, Josh Cates, Rob MacLeod, Ross Whitaker").empty()) \
      { \
      fullDescription += "\nAuthor(s): Gopal Veni, Salma Bengali, Greg Gardner, Alan Morris, Josh Cates, Rob MacLeod, Ross Whitaker"; \
      } \
    if (!std::string("This work was supported by ...").empty()) \
      { \
      fullDescription += "\nAcknowledgements: This work was supported by ..."; \
      } \
    TCLAP::CmdLine commandLine (fullDescription, \
       ' ', \
      "0.1.0" ); \
 \
      std::ostringstream msg; \
    msg.str("");msg << "Cardiac LGE-MRI image";    TCLAP::UnlabeledValueArg<std::string> inputImageArg("inputImage", msg.str(), 1, inputImage, "std::string", commandLine); \
 \
    msg.str("");msg << "Smoothness constraint for a surface";    TCLAP::UnlabeledValueArg<int> deltaSArg("deltaS", msg.str(), 1, deltaS, "int", commandLine); \
 \
    msg.str("");msg << "Selection of model";    TCLAP::UnlabeledValueArg<int> MdlOptionArg("MdlOption", msg.str(), 1, MdlOption, "int", commandLine); \
 \
    msg.str("");msg << "The segmented output image volume";    TCLAP::UnlabeledValueArg<std::string> outputImageArg("outputImage", msg.str(), 1, outputImage, "std::string", commandLine); \
 \
    msg.str("");msg << "The directory from which to import data files";    TCLAP::UnlabeledValueArg<std::string> inputDataDirectoryArg("inputDataDirectory", msg.str(), 1, inputDataDirectory, "std::string", commandLine); \
 \
    msg.str("");msg << "The epi mesh";    TCLAP::UnlabeledValueArg<std::string> epiMeshArg("epiMesh", msg.str(), 1, epiMesh, "std::string", commandLine); \
 \
    msg.str("");msg << "The endo mesh";    TCLAP::UnlabeledValueArg<std::string> endoMeshArg("endoMesh", msg.str(), 1, endoMesh, "std::string", commandLine); \
 \
    msg.str("");msg << "Center of mass row";    TCLAP::UnlabeledValueArg<float> rowArg("row", msg.str(), 1, row, "float", commandLine); \
 \
    msg.str("");msg << "Center of mass column";    TCLAP::UnlabeledValueArg<float> columnArg("column", msg.str(), 1, column, "float", commandLine); \
 \
    msg.str("");msg << "Center of mass Slice";    TCLAP::UnlabeledValueArg<float> sliceArg("slice", msg.str(), 1, slice, "float", commandLine); \
 \
    msg.str("");msg << "Echo the command line arguments (default: " << echoSwitch << ")"; \
    TCLAP::SwitchArg echoSwitchArg("", "echo", msg.str(), commandLine, echoSwitch); \
 \
    msg.str("");msg << "Produce xml description of command line arguments (default: " << xmlSwitch << ")"; \
    TCLAP::SwitchArg xmlSwitchArg("", "xml", msg.str(), commandLine, xmlSwitch); \
 \
    msg.str("");msg << "Address of a structure to store process information (progress, abort, etc.). (default: " << processInformationAddressString << ")"; \
    TCLAP::ValueArg<std::string > processInformationAddressStringArg("", "processinformationaddress", msg.str(), 0, processInformationAddressString, "std::string", commandLine); \
 \
    msg.str("");msg << "Filename in which to write simple return parameters (int, float, int-vector, etc.) as opposed to bulk return parameters (image, geometry, transform, measurement, table).";    TCLAP::ValueArg<std::string > returnParameterFileArg("", "returnparameterfile", msg.str(), 0, returnParameterFile, "std::string", commandLine); \
 \
try \
  { \
    /* Build a map of flag aliases to the true flag */ \
    std::map<std::string,std::string> flagAliasMap; \
    std::map<std::string,std::string> deprecatedFlagAliasMap; \
    std::map<std::string,std::string> longFlagAliasMap; \
    std::map<std::string,std::string> deprecatedLongFlagAliasMap; \
    /* Remap flag aliases to the true flag */ \
    std::vector<std::string> targs; \
    std::map<std::string,std::string>::iterator ait; \
    std::map<std::string,std::string>::iterator dait; \
    size_t ac; \
    for (ac=0; ac < static_cast<size_t>(argc); ++ac)  \
       {  \
       if (strlen(argv[ac]) == 2 && argv[ac][0]=='-') \
         { \
         /* short flag case */ \
         std::string tflag(argv[ac], 1, strlen(argv[ac])-1); \
         ait = flagAliasMap.find(tflag); \
         dait = deprecatedFlagAliasMap.find(tflag); \
         if (ait != flagAliasMap.end() || dait != deprecatedFlagAliasMap.end()) \
           { \
           if (ait != flagAliasMap.end()) \
             { \
             /* remap the flag */ \
             targs.push_back("-" + (*ait).second); \
             } \
           else if (dait != deprecatedFlagAliasMap.end()) \
             { \
             std::cout << "Flag \"" << argv[ac] << "\" is deprecated. Please use flag \"-" << (*dait).second << "\" instead. " << std::endl; \
             /* remap the flag */ \
             targs.push_back("-" + (*dait).second); \
             } \
           } \
         else \
           { \
           targs.push_back(argv[ac]); \
           } \
         } \
       else if (strlen(argv[ac]) > 2 && argv[ac][0]=='-' && argv[ac][1]=='-') \
         { \
         /* long flag case */ \
         std::string tflag(argv[ac], 2, strlen(argv[ac])-2); \
         ait = longFlagAliasMap.find(tflag); \
         dait = deprecatedLongFlagAliasMap.find(tflag); \
         if (ait != longFlagAliasMap.end() || dait != deprecatedLongFlagAliasMap.end()) \
           { \
           if (ait != longFlagAliasMap.end()) \
             { \
             /* remap the flag */ \
             targs.push_back("--" + (*ait).second); \
             } \
           else if (dait != deprecatedLongFlagAliasMap.end()) \
             { \
             std::cout << "Long flag \"" << argv[ac] << "\" is deprecated. Please use long flag \"--" << (*dait).second << "\" instead. " << std::endl; \
             /* remap the flag */ \
             targs.push_back("--" + (*dait).second); \
             } \
           } \
         else \
           { \
           targs.push_back(argv[ac]); \
           } \
         } \
       else if (strlen(argv[ac]) > 2 && argv[ac][0]=='-' && argv[ac][1]!='-') \
         { \
         /* short flag case where multiple flags are given at once ala */ \
         /* "ls -ltr" */ \
         std::string tflag(argv[ac], 1, strlen(argv[ac])-1); \
         std::string rflag("-"); \
         for (std::string::size_type fi=0; fi < tflag.size(); ++fi) \
           { \
           std::string tf(tflag, fi, 1); \
           ait = flagAliasMap.find(tf); \
           dait = deprecatedFlagAliasMap.find(tf); \
           if (ait != flagAliasMap.end() || dait != deprecatedFlagAliasMap.end()) \
             { \
             if (ait != flagAliasMap.end()) \
               { \
               /* remap the flag */ \
               rflag += (*ait).second; \
               } \
             else if (dait != deprecatedFlagAliasMap.end()) \
               { \
               std::cout << "Flag \"-" << tf << "\" is deprecated. Please use flag \"-" << (*dait).second << "\" instead. " << std::endl; \
               /* remap the flag */ \
               rflag += (*dait).second; \
               } \
             } \
           else \
             { \
             rflag += tf; \
             } \
           } \
         targs.push_back(rflag); \
         } \
       else \
         { \
         /* skip the argument without remapping (this is the case for any */ \
         /* arguments for flags */ \
         targs.push_back(argv[ac]); \
         } \
       } \
 \
   /* Remap args to a structure that CmdLine::parse() can understand*/ \
   std::vector<char*> vargs; \
   for (ac = 0; ac < targs.size(); ++ac) \
     {  \
     vargs.push_back(const_cast<char *>(targs[ac].c_str())); \
     } \
    commandLine.parse ( vargs.size(), (char**) &(vargs[0]) ); \
    inputImage = inputImageArg.getValue(); \
    deltaS = deltaSArg.getValue(); \
    MdlOption = MdlOptionArg.getValue(); \
    outputImage = outputImageArg.getValue(); \
    inputDataDirectory = inputDataDirectoryArg.getValue(); \
    epiMesh = epiMeshArg.getValue(); \
    endoMesh = endoMeshArg.getValue(); \
    row = rowArg.getValue(); \
    column = columnArg.getValue(); \
    slice = sliceArg.getValue(); \
    echoSwitch = echoSwitchArg.getValue(); \
    xmlSwitch = xmlSwitchArg.getValue(); \
    processInformationAddressString = processInformationAddressStringArg.getValue(); \
    returnParameterFile = returnParameterFileArg.getValue(); \
  } \
catch ( TCLAP::ArgException e ) \
  { \
  std::cerr << "error: " << e.error() << " for arg " << e.argId() << std::endl; \
  return ( EXIT_FAILURE ); \
  }
#define GENERATE_ECHOARGS \
if (echoSwitch) \
{ \
std::cout << "Command Line Arguments" << std::endl; \
std::cout << "    inputImage: " << inputImage << std::endl; \
std::cout << "    deltaS: " << deltaS << std::endl; \
std::cout << "    MdlOption: " << MdlOption << std::endl; \
std::cout << "    outputImage: " << outputImage << std::endl; \
std::cout << "    inputDataDirectory: " << inputDataDirectory << std::endl; \
std::cout << "    epiMesh: " << epiMesh << std::endl; \
std::cout << "    endoMesh: " << endoMesh << std::endl; \
std::cout << "    row: " << row << std::endl; \
std::cout << "    column: " << column << std::endl; \
std::cout << "    slice: " << slice << std::endl; \
std::cout << "    echoSwitch: " << echoSwitch << std::endl; \
std::cout << "    xmlSwitch: " << xmlSwitch << std::endl; \
std::cout << "    processInformationAddressString: " << processInformationAddressString << std::endl; \
std::cout << "    returnParameterFile: " << returnParameterFile << std::endl; \
}
#define GENERATE_ProcessInformationAddressDecoding \
ModuleProcessInformation *CLPProcessInformation = 0; \
if (processInformationAddressString != "") \
{ \
sscanf(processInformationAddressString.c_str(), "%p", &CLPProcessInformation); \
}
#define PARSE_ARGS GENERATE_LOGO;GENERATE_XML;GENERATE_TCLAP;GENERATE_ECHOARGS;GENERATE_ProcessInformationAddressDecoding;
